
package visual;

import DAO.NCDAO;
import DTO.NcDTO;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;

public class EditNC extends javax.swing.JFrame {
	
	private static String Nome_Nc, responsavel_Nc, local_Nc, descricao_Nc, ID_NC, IdPlano;
	
	public void setTxtNome(String txtNome) {
		Nome_Nc = txtNome;
	}

	public void setTxtResponsavelNc(String resp) {
		responsavel_Nc = resp;
	}

	public void setLocalNC(String local) {
		local_Nc = local;
	}

	public void setDescricao(String descricao) {
		descricao_Nc = descricao;
	}

	public void SetIdNc(int id) {

		ID_NC = String.valueOf(id);
	}

	public void SetIdplano(int id) {

		IdPlano = String.valueOf(id);
	
	}

	
	public void setALL() {
		txtNome_Nc.setText(Nome_Nc);
		txtresponsavel_Nc.setText(responsavel_Nc);
		txtlocal_Nc.setText(local_Nc);
		txtdescricao_Nc.setText(descricao_Nc);
		
		txtID_NC.setText(ID_NC);
		txtIdPlano.setText(IdPlano);
	}
	public void pesquisar(String Pesquisa) {
		NCDAO pesq = new NCDAO();
		pesq.pesquisaeditar(Pesquisa);
		
		EditNC editarNc = new EditNC();
		editarNc.setVisible(true);
		
	}
	

	

	public String getNome_Nc() {
		return Nome_Nc;
	}

	public String getResponsavel_Nc() {
		return responsavel_Nc;
	}

	public String getLocal_Nc() {
		return local_Nc;
	}

	public String getDescricao_Nc() {
		return descricao_Nc;
	}

	public String getID_NC() {
		return ID_NC;
	}

	public String getIdPlano() {
		return IdPlano;
	}

	public EditNC() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtNome_Nc = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txtresponsavel_Nc = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtlocal_Nc = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtdescricao_Nc = new javax.swing.JTextArea();
		btnCancelar = new javax.swing.JButton();
		btnSalvar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Inserir Não Conformidade");
		setLocationByPlatform(true);

		jLabel1.setText("Título da Não conformidade:");

		jLabel2.setText("Responsável:");

		jLabel3.setText("Local onde ocorreu:");

		txtlocal_Nc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtlocal_NcActionPerformed(evt);
			}
		});

		jLabel4.setText("Descrição da NC");

		txtdescricao_Nc.setColumns(20);
		txtdescricao_Nc.setRows(5);
		jScrollPane1.setViewportView(txtdescricao_Nc);

		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		btnSalvar.setText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		lblNewLabel = new JLabel("ID NC");

		txtID_NC = new JTextField();
		txtID_NC.setEditable(false);
		txtID_NC.setColumns(10);

		lblNewLabel_1 = new JLabel("ID Plano de A\u00E7\u00E3o");

		txtIdPlano = new JTextField();
		txtIdPlano.setEditable(false);
		txtIdPlano.setColumns(10);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
				.addGap(197)
				.addGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(txtlocal_Nc, 201, 201, 201)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING, false).addGroup(layout
										.createSequentialGroup().addComponent(txtresponsavel_Nc, 201, 201, 201)
										.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(txtIdPlano, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
										.addGroup(Alignment.LEADING, layout.createSequentialGroup()
												.addComponent(txtNome_Nc, 201, 201, 201).addGap(70)
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(lblNewLabel_1).addComponent(txtID_NC,
																GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)))))
						.addGap(22))
						.addGroup(layout.createSequentialGroup().addGap(66)
								.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE).addGap(246))
						.addGroup(layout.createSequentialGroup().addGap(52)
								.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE).addGap(231))))
				.addGroup(layout.createSequentialGroup().addGap(154)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
								.addComponent(btnCancelar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGap(146).addComponent(btnSalvar, GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
								.addGap(137))
								.addGroup(layout.createSequentialGroup().addGap(99)
										.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGap(245))))
				.addGroup(layout.createSequentialGroup().addContainerGap(252, Short.MAX_VALUE).addComponent(jLabel1)
						.addGap(106).addComponent(lblNewLabel).addGap(55))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE).addGap(6)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
								.addGap(21).addComponent(jLabel1).addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(txtNome_Nc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jLabel2)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(txtresponsavel_Nc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jLabel3)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(txtlocal_Nc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(18).addComponent(jLabel4))
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(lblNewLabel)
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addComponent(txtID_NC, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(lblNewLabel_1)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(txtIdPlano,
												GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(btnCancelar)
								.addComponent(btnSalvar))
						.addGap(52)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

	private void txtlocal_NcActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
		Home home = new Home();
		home.setVisible(true);
		dispose();
	}

									//mudar para atualizar
	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) { // botão salvar;
		NcDTO objnc = new NcDTO();
		objnc.setNome_Nc(txtNome_Nc.getText());
		objnc.setResponsavel_Nc(txtresponsavel_Nc.getText());
		objnc.setLocal_Nc(txtlocal_Nc.getText());
		objnc.setDescricao_Nc(txtdescricao_Nc.getText());

		NCDAO objncdao = new NCDAO();
		objncdao.registerNC(objnc);
		dispose();

	}


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EditNC().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField txtNome_Nc;
	private javax.swing.JTextArea txtdescricao_Nc;
	private javax.swing.JTextField txtlocal_Nc;
	private javax.swing.JTextField txtresponsavel_Nc;
	private JLabel lblNewLabel;
	private JTextField txtID_NC;
	private JLabel lblNewLabel_1;
	private JTextField txtIdPlano;
	// End of variables declaration
}
