
package visual;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DAO.NCDAO;
import DTO.NcDTO;
import java.awt.Color;
import java.awt.Toolkit;

public class HomeNC_2 extends javax.swing.JFrame {

	public HomeNC_2() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(HomeNC_2.class.getResource("/imagens/checkIcon.jpg")));
		setTitle("NC LOG");
		setBackground(Color.LIGHT_GRAY);

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtSearch = new javax.swing.JTextField();
		btnSearch = new javax.swing.JButton();
		btnInserirNC = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableNC = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Pesquisa:");

		btnSearch.setText("Pesquisar");
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});

		btnInserirNC.setText("Inserir NC");
		btnInserirNC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnInserirNCActionPerformed(evt);
			}
		});

		tableNC.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "ID NC", "Nome", "Responsável", "Local" }));
		jScrollPane1.setViewportView(tableNC);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(6, 6, 6).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 177,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btnSearch).addGap(18, 18, 18).addComponent(btnInserirNC)))
				.addContainerGap(85, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSearch).addComponent(btnInserirNC))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {

		listarNc();
	}

	private void btnInserirNCActionPerformed(java.awt.event.ActionEvent evt) {
		CreateNC cn = new CreateNC();
		cn.setVisible(true);
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomeNC_2().setVisible(true);
			}
		});
	}

	private javax.swing.JButton btnInserirNC;
	private javax.swing.JButton btnSearch;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableNC;
	private javax.swing.JTextField txtSearch;
	private String pesquisa;
	private String resp_nc;

	public void setPesquisa(String pesquisa) {
		this.pesquisa = pesquisa;
	}

	public String getPesquisa() {
		return pesquisa;

	}

	public void setResp_nc(String resp_nc) {
		this.resp_nc = resp_nc;

	}

	public String getRespNc() {
		return resp_nc;
	}

	private void listarNc() { // adiciona os dados das NCs ao jTable;
		try {

			NCDAO objnc = new NCDAO();
			this.setPesquisa(txtSearch.getText());

			DefaultTableModel model = (DefaultTableModel) tableNC.getModel();
			model.setNumRows(0);

			// cria um arrayList com os dados do objnc.pesquisarNC();
			ArrayList<NcDTO> lista = objnc.pesquisarNC(this.getPesquisa());

			// transforma em tabela;
			for (int num = 0; num < lista.size(); num++) {
				model.addRow(new Object[] { lista.get(num).getId_Nc(), lista.get(num).getNome_Nc(),
						lista.get(num).getResponsavel_Nc(), lista.get(num).getLocal_Nc(),
						lista.get(num).getId_Plano() });

			}

		} catch (Exception erro) {
			JOptionPane.showMessageDialog(null, "HomeNC_2 listarNc " + erro);
		}

	}
}
