//
//package visual;
//
//import java.sql.SQLException;
//import java.util.ArrayList;
//
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//
//import DAO.NCDAO;
//import DTO.NcDTO;
//import java.awt.Color;
//import java.awt.Toolkit;
//import javax.swing.JButton;
//import javax.swing.GroupLayout.Alignment;
//import javax.swing.GroupLayout;
//import javax.swing.LayoutStyle.ComponentPlacement;
//import javax.swing.JTextField;
//import javax.swing.JLabel;
//import java.awt.event.ActionListener;
//import java.awt.event.ActionEvent;
//import javax.swing.JMenuBar;
//import javax.swing.JMenu;
//
//public class HomeNC_2 extends javax.swing.JFrame {
//
//	public HomeNC_2() {
//		setIconImage(Toolkit.getDefaultToolkit().getImage(HomeNC_2.class.getResource("/imagens/checkIcon.jpg")));
//		setTitle("NC LOG");
//		setBackground(Color.LIGHT_GRAY);
//
//		initComponents();
//	}
//
//	/**
//	 * This method is called from within the constructor to initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is always
//	 * regenerated by the Form Editor.
//	 */
//	@SuppressWarnings("unchecked")
//	// <editor-fold defaultstate="collapsed" desc="Generated Code">
//	private void initComponents() {
//
//		jLabel1 = new javax.swing.JLabel();
//		jLabel1.setToolTipText("Pesquise o nome da n\u00E3o conformidade");
//		txtSearch = new javax.swing.JTextField();
//		btnSearch = new javax.swing.JButton();
//		btnInserirNC = new javax.swing.JButton();
//		tblnc = new javax.swing.JScrollPane();
//		tableNC = new javax.swing.JTable();
//
//		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//		jLabel1.setText("Pesquisa:");
//
//		btnSearch.setText("Pesquisar");
//		btnSearch.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				btnSearchActionPerformed(evt);
//			}
//		});
//
//		btnInserirNC.setText("Inserir NC");
//		btnInserirNC.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				btnInserirNCActionPerformed(evt);
//			}
//		});
//
//		tableNC.setModel(
//				new javax.swing.table.DefaultTableModel(
//						new Object[][] { { null, null, null, null }, {  null, null, null, null },
//								{  null, null, null, null}, {  null, null, null, null } },
//						new String[] { "ID NC", "Nome", "Responsável", "Local"}));
//		tblnc.setViewportView(tableNC);
//		
//		JButton btnEditarNc = new JButton("Editar NC");
//		btnEditarNc.addActionListener(new ActionListener() {
//			public void actionPerformed(ActionEvent e) {
//				EditarNc();
//			}
//		});
//		btnEditarNc.setToolTipText("Edita N\u00E3o Conformidade selecionada");
//		
//		btnverplano = new JButton("Plano de A\u00E7\u00E3o");
//		btnverplano.addActionListener(new ActionListener() {
//			
//			
//			public void actionPerformed(ActionEvent e) {
//				
//				
//			}
//		});
//		btnverplano.setToolTipText("Visualizar plano de a\u00E7\u00E3o da NC selecionada");
//
//		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//		layout.setHorizontalGroup(
//			layout.createParallelGroup(Alignment.LEADING)
//				.addGroup(layout.createSequentialGroup()
//					.addGap(0)
//					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
//						.addGroup(layout.createSequentialGroup()
//							.addGap(6)
//							.addComponent(tblnc, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
//						.addGroup(layout.createSequentialGroup()
//							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
//							.addPreferredGap(ComponentPlacement.RELATED)
//							.addComponent(txtSearch, GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
//							.addGap(18)
//							.addComponent(btnSearch, GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
//							.addGap(120)))
//					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
//						.addGroup(layout.createSequentialGroup()
//							.addGroup(layout.createParallelGroup(Alignment.LEADING)
//								.addGroup(layout.createSequentialGroup()
//									.addGap(22)
//									.addComponent(btnInserirNC, GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
//									.addPreferredGap(ComponentPlacement.RELATED))
//								.addGroup(layout.createSequentialGroup()
//									.addPreferredGap(ComponentPlacement.UNRELATED)
//									.addComponent(btnverplano)))
//							.addGap(0))
//						.addGroup(layout.createSequentialGroup()
//							.addPreferredGap(ComponentPlacement.RELATED)
//							.addComponent(btnEditarNc)
//							.addContainerGap())))
//		);
//		layout.setVerticalGroup(
//			layout.createParallelGroup(Alignment.LEADING)
//				.addGroup(layout.createSequentialGroup()
//					.addGap(20)
//					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
//						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
//						.addComponent(txtSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
//						.addComponent(btnSearch)
//						.addComponent(btnInserirNC))
//					.addPreferredGap(ComponentPlacement.RELATED)
//					.addGroup(layout.createParallelGroup(Alignment.LEADING)
//						.addComponent(tblnc, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
//						.addGroup(layout.createSequentialGroup()
//							.addComponent(btnverplano)
//							.addPreferredGap(ComponentPlacement.RELATED)
//							.addComponent(btnEditarNc)))
//					.addGap(29))
//		);
//		getContentPane().setLayout(layout);
//
//		pack();
//	}// </editor-fold>
//
//	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
//
//		listarNc();
//	}
//
//	private void btnInserirNCActionPerformed(java.awt.event.ActionEvent evt) {
//		CreateNC cn = new CreateNC();
//		cn.setVisible(true);
//		dispose();
//	}
//
//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(HomeNC_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new HomeNC_2().setVisible(true);
//			}
//		});
//	}
//
//	private javax.swing.JButton btnInserirNC;
//	private javax.swing.JButton btnSearch;
//	private javax.swing.JLabel jLabel1;
//	private javax.swing.JScrollPane tblnc;
//	private javax.swing.JTable tableNC;
//	private javax.swing.JTextField txtSearch;
//	private String pesquisa;
//	private String resp_nc;
//	private JButton btnverplano;
//
//	public void setPesquisa(String pesquisa) {
//		this.pesquisa = pesquisa;
//	}
//
//	public String getPesquisa() {
//		return pesquisa;
//
//	}
//
//	public void setResp_nc(String resp_nc) {
//		this.resp_nc = resp_nc;
//
//	}
//
//	public String getRespNc() {
//		return resp_nc;
//	}
//
//	private void listarNc() { // adiciona os dados das NCs ao jTable;
//		try {
//
//			NCDAO objnc = new NCDAO();
//			this.setPesquisa(txtSearch.getText());
//
//			DefaultTableModel model = (DefaultTableModel) tableNC.getModel();
//			model.setNumRows(0);
//
//			// cria um arrayList com os dados do objnc.pesquisarNC();
//			ArrayList<NcDTO>	 lista = objnc.pesquisarNC(this.getPesquisa());
//
//			// transforma em tabela;
//			for (int num = 0; num < lista.size(); num++) {
//				model.addRow(new Object[] { lista.get(num).getId_Nc(), lista.get(num).getNome_Nc(),
//						lista.get(num).getResponsavel_Nc(), lista.get(num).getLocal_Nc(),
//						lista.get(num).getId_Plano(), lista.get(num).getDescricao_Nc() });
//
//			}
//
//		} catch (Exception erro) {
//			JOptionPane.showMessageDialog(null, "HomeNC_2 listarNc " + erro);
//		}
//
//	}
//	
//	
//	private void EditarNc() {
//		int setar = tableNC.getSelectedRow();
//	//	txtID.setText((tableNC.getModel().getValueAt(setar, 0).toString()));
//		String id_nc= tableNC.getModel().getValueAt(setar, 0).toString();
//		
//		
//		EditNC cnc = new EditNC();
//		cnc.pesquisar(id_nc);
//		
//		/*
//		NCDAO ndao = new NCDAO();
//		ndao.pesquisaeditar(id_nc);
//		*/
//		
//		
//	}
//}
